# Generated by Django 5.1.4 on 2025-01-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_alter_word_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(choices=[('Verb', 'Verb'), ('Phrasal Verb', 'Phrasal Verb'), ('Adjective', 'Adjective'), ('Noun', 'Noun'), ('Adverb', 'Adverb'), ('Prepostion', 'Prepostion')], max_length=30),
        ),
    ]
