# Generated by Django 5.1.4 on 2025-02-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0009_offlinecoaching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinecoaching',
            name='duration',
            field=models.CharField(choices=[('1 month', '1 month'), ('3 months', '3 months'), ('6 months', '6 months'), ('1 Year', '1 Year')], max_length=30),
        ),
    ]
