# Generated by Django 5.1.4 on 2025-04-09 14:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0011_alter_word_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlinecoaching',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
